[options]
addons_path = /home/broadtech/odoo/odoo-15.0+e.20230222/odoo/addons,/home/broadtech/project_addons/camelion_stage/camelion
;
db_name = camelion_stage_may14_2026
db_password = admin
workers = 2
port = 443
server_wide_modules = web,queue_job,integration,integration_woocommerce
host = broadtech:8069
[queue_job]
channels = root:1
